// Panel configuration. Every number here is DERIVED and said so, because a
// panel that ships "10" as a rate limit without a reason is a panel that will
// be "simplified" to 100 by the next person.
//
// FAIL-CLOSED BY DEFAULT: the panel is OFF unless PANEL_ENABLED is exactly "1".
// A repo with one database and no staging environment (AGENTS.md, "Test every
// change in a sandbox") earns its keep by making new customer-facing reach
// something the operator turns on deliberately.
import { z } from "zod";

const truthy = z.enum(["1", "true", "yes"]).optional();

const Schema = z.object({
  PANEL_ENABLED: truthy,
  // The host the panel will answer on. A handoff ticket is bound to an
  // audience; comparing it against this — not against the request's Host —
  // is what stops a ticket minted for a preview host from being spent in prod.
  PANEL_AUDIENCE_HOST: z.string().default("pay.mntad.com"),
  // Shared with MNTAD, generated by Ibrahim, never by this app. Required the
  // moment the panel is on: a panel that accepts handoffs without a signing
  // secret accepts them from anyone.
  MNTAD_SAMAPAY_HANDOFF_SECRET: z.string().min(32).optional(),
  PANEL_COOKIE_NAME: z.string().default("spnl"),
  PANEL_STATE_COOKIE_NAME: z.string().default("spnl_st"),
  // 12 h, not 30 d: this session can mint and revoke API keys that receive
  // money. The cost of a short TTL is one email code a day, not a support ticket.
  PANEL_SESSION_TTL_SEC: z.coerce.number().int().min(300).max(43200).default(43200),
  // 10 min matches MNTAD's own OTP TTL (lib/auth), so "the code expired" means
  // the same thing on both sides of the estate.
  PANEL_LOGIN_CODE_TTL_SEC: z.coerce.number().int().min(120).max(900).default(600),
  PANEL_CODE_MAX_ATTEMPTS: z.coerce.number().int().min(3).max(10).default(5),
  // FINAL-RULINGS B#6: the handoff ticket lives 60 s. Not a round number —
  // the time it takes a human to click "Continue" and a browser to POST back,
  // with a slow-phone margin, and no longer.
  PANEL_HANDOFF_TTL_SEC: z.coerce.number().int().min(30).max(120).default(60),
  PANEL_MAIL_TRANSPORT: z.enum(["sendmail", "log", "none"]).default("none"),
  PANEL_SENDMAIL_PATH: z.string().default("/usr/sbin/sendmail"),
  // Measured on this box: postfix's sendmail, mntad.com is in
  // virtual_mailbox_domains, `mail.mntad.com` resolves to this host (so the SPF
  // `+mx` on mntad.com authorizes it as a sender) and the DKIM SigningTable maps
  // *@mntad.com to default._domainkey.mntad.com. noreply@mntad.com is a real
  // mailbox here, so a bounce or a reply has somewhere to land instead of
  // becoming a support ticket about a code that never came.
  PANEL_MAIL_FROM: z.string().default("noreply@mntad.com"),
  // Operator-only allowlist for the http+loopback webhook exception (MNTAD and
  // SamaPay share this box and talk over http://127.0.0.1:3090). Comma-list of
  // hostnames. THIS IS NEVER A MERCHANT INPUT — pay-dashboard.md A.8.
  PANEL_WEBHOOK_ALLOWED_HOSTNAMES: z.string().default(""),
  // SEED_ENCRYPTION_KEY is already this service's AEAD root for the
  // webhook-secret subkey (src/keys/webhook-secret.ts). The panel's TOTP secret
  // gets its OWN HKDF subkey under the same root; see crypto.ts on why the
  // info string is domain-separated rather than reusing the webhook one.
  SEED_ENCRYPTION_KEY: z.string().min(16).optional(),
});

export type PanelConfig = Readonly<{
  enabled: boolean;
  audienceHost: string;
  handoffSecret: string | null;
  cookieName: string;
  stateCookieName: string;
  sessionTtlSec: number;
  codeTtlSec: number;
  codeMaxAttempts: number;
  handoffTtlSec: number;
  mailTransport: "sendmail" | "log" | "none";
  sendmailPath: string;
  mailFrom: string;
  webhookAllowedHostnames: readonly string[];
  seedEncryptionKey: string | null;
}>;

export class PanelConfigError extends Error {
  override name = "PanelConfigError";
}

export function readPanelConfig(env: NodeJS.ProcessEnv = process.env): PanelConfig {
  const parsed = Schema.safeParse(env);
  if (!parsed.success) {
    throw new PanelConfigError(`panel config refused to start: ${parsed.error.issues.map((i) => `${i.path.join(".")} — ${i.message}`).join("; ")}`);
  }
  const c = parsed.data;
  const enabled = c.PANEL_ENABLED === "1" || c.PANEL_ENABLED === "true" || c.PANEL_ENABLED === "yes";
  if (enabled && !c.MNTAD_SAMAPAY_HANDOFF_SECRET) {
    // Naming the missing variable is safe; naming a value is not.
    throw new PanelConfigError("PANEL_ENABLED is on but MNTAD_SAMAPAY_HANDOFF_SECRET is unset — refusing to start a panel that would accept unsigned handoffs.");
  }
  return Object.freeze({
    enabled,
    audienceHost: c.PANEL_AUDIENCE_HOST,
    handoffSecret: c.MNTAD_SAMAPAY_HANDOFF_SECRET ?? null,
    cookieName: c.PANEL_COOKIE_NAME,
    stateCookieName: c.PANEL_STATE_COOKIE_NAME,
    sessionTtlSec: c.PANEL_SESSION_TTL_SEC,
    codeTtlSec: c.PANEL_LOGIN_CODE_TTL_SEC,
    codeMaxAttempts: c.PANEL_CODE_MAX_ATTEMPTS,
    handoffTtlSec: c.PANEL_HANDOFF_TTL_SEC,
    mailTransport: c.PANEL_MAIL_TRANSPORT,
    sendmailPath: c.PANEL_SENDMAIL_PATH,
    mailFrom: c.PANEL_MAIL_FROM,
    webhookAllowedHostnames: Object.freeze(c.PANEL_WEBHOOK_ALLOWED_HOSTNAMES.split(",").map((s) => s.trim()).filter(Boolean)),
    seedEncryptionKey: c.SEED_ENCRYPTION_KEY ?? null,
  });
}
