-- PANEL IDENTITY (pay.mntad.com merchant dashboard, phase 1) — EXPAND ONLY.
-- Generated by scripts/gen-panel-migration.ts as a FILE-TO-FILE diff
-- (prisma migrate diff --from-migrations prisma/migrations --to-schema-datamodel
-- prisma/schema.prisma) against a shadow database on a throwaway cluster. No
-- real database was touched to produce this file.
--
-- Nothing here drops, rewrites or backfills anything. Every table and column is
-- new, every column is nullable or has a default, and no existing row changes
-- meaning. Nothing in samapay's runtime reads or writes these tables until the
-- panel is enabled, and the panel is OFF unless PANEL_ENABLED=1 (src/panel/config.ts).
--
-- APPLY IS IBRAHIM'S KEYSTROKE: `prisma migrate deploy` in samapay. This file is
-- the thing to be approved, not something an agent applies.
--
-- CreateEnum
CREATE TYPE "AccountRole" AS ENUM ('owner', 'viewer');

-- CreateEnum
CREATE TYPE "LoginCodePurpose" AS ENUM ('sign_up', 'sign_in');

-- AlterTable
ALTER TABLE "client_keys" ADD COLUMN     "created_from_ip" TEXT,
ADD COLUMN     "created_via" TEXT NOT NULL DEFAULT 'cli',
ADD COLUMN     "webhook_updated_at" TIMESTAMP(3);

-- AlterTable
ALTER TABLE "webhook_deliveries" ADD COLUMN     "test_only" BOOLEAN NOT NULL DEFAULT false;

-- CreateTable
CREATE TABLE "accounts" (
    "id" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "display_name" TEXT,
    "mntad_user_id" TEXT,
    "mntad_merchant_id" TEXT,
    "totp_secret_enc" TEXT,
    "totp_enabled_at" TIMESTAMP(3),
    "disabled_at" TIMESTAMP(3),
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "last_sign_in_at" TIMESTAMP(3),

    CONSTRAINT "accounts_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "account_clients" (
    "id" TEXT NOT NULL,
    "account_id" TEXT NOT NULL,
    "client_id" TEXT NOT NULL,
    "role" "AccountRole" NOT NULL DEFAULT 'owner',
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "account_clients_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "login_codes" (
    "id" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "purpose" "LoginCodePurpose" NOT NULL,
    "code_hash" TEXT NOT NULL,
    "expires_at" TIMESTAMP(3) NOT NULL,
    "consumed_at" TIMESTAMP(3),
    "attempts" INTEGER NOT NULL DEFAULT 0,
    "max_attempts" INTEGER NOT NULL DEFAULT 5,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_from_ip" TEXT,
    "sent_to" TEXT NOT NULL,

    CONSTRAINT "login_codes_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "panel_sessions" (
    "id" TEXT NOT NULL,
    "token_hash" TEXT NOT NULL,
    "account_id" TEXT NOT NULL,
    "csrf_token" TEXT NOT NULL,
    "via" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "last_seen_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "expires_at" TIMESTAMP(3) NOT NULL,
    "revoked_at" TIMESTAMP(3),
    "last_seen_ip" TEXT,
    "user_agent" TEXT,

    CONSTRAINT "panel_sessions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "panel_backup_codes" (
    "id" TEXT NOT NULL,
    "account_id" TEXT NOT NULL,
    "code_hash" TEXT NOT NULL,
    "used_at" TIMESTAMP(3),
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "panel_backup_codes_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "handoff_tickets" (
    "id" TEXT NOT NULL,
    "mntad_user_id" TEXT NOT NULL,
    "mntad_merchant_id" TEXT NOT NULL,
    "samapay_client_id" TEXT NOT NULL,
    "audience_host" TEXT NOT NULL,
    "state_hash" CHAR(64) NOT NULL,
    "return_path" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "expires_at" TIMESTAMP(3) NOT NULL,
    "consumed_at" TIMESTAMP(3),
    "consumed_ip" TEXT,
    "session_id" TEXT,

    CONSTRAINT "handoff_tickets_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "accounts_email_key" ON "accounts"("email");

-- CreateIndex
CREATE UNIQUE INDEX "accounts_mntad_user_id_key" ON "accounts"("mntad_user_id");

-- CreateIndex
CREATE INDEX "account_clients_client_id_idx" ON "account_clients"("client_id");

-- CreateIndex
CREATE UNIQUE INDEX "account_clients_account_id_client_id_key" ON "account_clients"("account_id", "client_id");

-- CreateIndex
CREATE INDEX "login_codes_email_purpose_created_at_idx" ON "login_codes"("email", "purpose", "created_at");

-- CreateIndex
CREATE INDEX "login_codes_expires_at_idx" ON "login_codes"("expires_at");

-- CreateIndex
CREATE UNIQUE INDEX "panel_sessions_token_hash_key" ON "panel_sessions"("token_hash");

-- CreateIndex
CREATE INDEX "panel_sessions_account_id_idx" ON "panel_sessions"("account_id");

-- CreateIndex
CREATE INDEX "panel_sessions_expires_at_idx" ON "panel_sessions"("expires_at");

-- CreateIndex
CREATE UNIQUE INDEX "panel_backup_codes_code_hash_key" ON "panel_backup_codes"("code_hash");

-- CreateIndex
CREATE INDEX "panel_backup_codes_account_id_idx" ON "panel_backup_codes"("account_id");

-- CreateIndex
CREATE INDEX "handoff_tickets_expires_at_idx" ON "handoff_tickets"("expires_at");

-- CreateIndex
CREATE INDEX "handoff_tickets_mntad_merchant_id_idx" ON "handoff_tickets"("mntad_merchant_id");

-- AddForeignKey
ALTER TABLE "account_clients" ADD CONSTRAINT "account_clients_account_id_fkey" FOREIGN KEY ("account_id") REFERENCES "accounts"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "account_clients" ADD CONSTRAINT "account_clients_client_id_fkey" FOREIGN KEY ("client_id") REFERENCES "clients"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "panel_sessions" ADD CONSTRAINT "panel_sessions_account_id_fkey" FOREIGN KEY ("account_id") REFERENCES "accounts"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "panel_backup_codes" ADD CONSTRAINT "panel_backup_codes_account_id_fkey" FOREIGN KEY ("account_id") REFERENCES "accounts"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "handoff_tickets" ADD CONSTRAINT "handoff_tickets_samapay_client_id_fkey" FOREIGN KEY ("samapay_client_id") REFERENCES "clients"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
