// COVERS: prisma/schema.prisma
//
// GENERATES the panel-identity migration SQL by FILE-TO-FILE DIFF, which is the
// rule (AGENTS.md / samaprime-deploy-and-rehearsal): never generate a migration
// against a real database, and read every statement before it is applied.
//
// `prisma migrate diff --from-migrations` insists on a shadow database because
// it applies the whole migration history into it before comparing. This script
// therefore creates that shadow ON THE DISPOSABLE CLUSTER it is being run
// inside — the sanctioned one:
//   bash /www/wwwroot/samaprime.com/scripts/throwaway-pg.sh \
//     ./node_modules/.bin/tsx scripts/gen-panel-migration.ts
// It REFUSES anything that is not a throwaway cluster, using the same proofs
// scripts/throwaway-sandbox.ts uses (host, port, database name, the wrapper's
// marker row), so a typo in a shell history cannot point a shadow at
// production's 5432.
import { spawnSync } from "node:child_process";
import { mkdirSync, writeFileSync } from "node:fs";
import { prisma } from "@/db/client.js";

function refuse(msg: string): never {
  console.error(`gen-panel-migration: REFUSED — ${msg}`);
  process.exit(2);
}

const raw = process.env.DATABASE_URL;
if (!raw) refuse("DATABASE_URL is not set — run inside samaprime's scripts/throwaway-pg.sh");
let url: URL;
try { url = new URL(raw); } catch { refuse("DATABASE_URL does not parse"); }
if (url.hostname !== "127.0.0.1") refuse(`host is ${url.hostname}, not 127.0.0.1`);
if (url.pathname !== "/throwaway") refuse(`database is ${url.pathname}, not the wrapper's "throwaway"`);
const port = Number(url.port);
if (port === 5432 || port === 5433) refuse(`port ${port} is a real instance on this box, not a throwaway`);
if (port < 55000 || port > 59999) refuse(`port ${port} is outside the throwaway range the wrapper allocates`);

const marker = await prisma.$queryRawUnsafe<Array<{ d: string | null }>>(
  `select setting as d from pg_settings where name = 'data_directory'`,
);
const dataDir = marker[0]?.d ?? "";
if (!dataDir.includes("throwaway-pg-")) refuse(`data_directory "${dataDir}" is not a throwaway-pg data directory`);

const SHADOW = "shadow_sandbox";
await prisma.$executeRawUnsafe(`DROP DATABASE IF EXISTS "${SHADOW}"`);
await prisma.$executeRawUnsafe(`CREATE DATABASE "${SHADOW}"`);
const shadow = new URL(raw);
shadow.pathname = `/${SHADOW}`;

// `node_modules/.bin/prisma` is a POSIX shim, not a JS entry — spawning it under
// process.execPath is how you get "SyntaxError: Invalid or unexpected token"
// from a shell script. Resolve the package's own build entry instead.
const PRISMA_ENTRY = "node_modules/prisma/build/index.js";
const DIFF_ARGS = [
  PRISMA_ENTRY, "migrate", "diff",
  "--from-migrations", "prisma/migrations",
  "--to-schema-datamodel", "prisma/schema.prisma",
  "--shadow-database-url", shadow.toString(),
  "--script",
];
const diff = spawnSync(process.execPath, DIFF_ARGS, { encoding: "utf8" });
if (diff.status !== 0) refuse(`prisma migrate diff exited ${diff.status}: ${diff.stderr?.slice(0, 400)}`);
const sql = diff.stdout.trim();
if (!sql) refuse("the diff produced no SQL — the schema already matches the migrations, so there is nothing to approve");
if (/DROP TABLE|DROP COLUMN|DROP NOT NULL|TRUNCATE|DELETE FROM/i.test(sql)) {
  refuse(`the diff contains a DESTRUCTIVE statement — an EXPAND migration must not:\n${sql.slice(0, 2000)}`);
}

const dir = "prisma/migrations/20261001000000_panel_identity";
mkdirSync(dir, { recursive: true });
const header =
`-- PANEL IDENTITY (pay.mntad.com merchant dashboard, phase 1) — EXPAND ONLY.
-- Generated by scripts/gen-panel-migration.ts as a FILE-TO-FILE diff
-- (prisma migrate diff --from-migrations prisma/migrations --to-schema-datamodel
-- prisma/schema.prisma) against a shadow database on a throwaway cluster. No
-- real database was touched to produce this file.
--
-- Nothing here drops, rewrites or backfills anything. Every table and column is
-- new, every column is nullable or has a default, and no existing row changes
-- meaning. Nothing in samapay's runtime reads or writes these tables until the
-- panel is enabled, and the panel is OFF unless PANEL_ENABLED=1 (src/panel/config.ts).
--
-- APPLY IS IBRAHIM'S KEYSTROKE: \`prisma migrate deploy\` in samapay. This file is
-- the thing to be approved, not something an agent applies.
--
`;
writeFileSync(`${dir}/migration.sql`, `${header}${sql}\n`);
await prisma.$executeRawUnsafe(`DROP DATABASE IF EXISTS "${SHADOW}"`);
console.log(`WROTE ${dir}/migration.sql (${sql.split("\n").length} lines of SQL)`);
console.log("--- BEGIN SQL (review every statement) ---");
console.log(sql);
console.log("--- END SQL ---");
