// COVERS: src/chain/seed/import.ts src/chain/seed/secret-input.ts src/chain/seed/ops-gate.ts src/chain/seed/vault-proof.ts src/chain/seed/vault.ts src/chain/seed/master-seed.ts scripts/import-master-seed.ts scripts/prove-vault.ts
//
// SEED IMPORT + VAULT PROOF (contract §8.1–8.2), on a THROWAWAY cluster only:
//
//   bash /www/wwwroot/samaprime.com/scripts/throwaway-pg.sh \
//     ./node_modules/.bin/tsx scripts/throwaway-sandbox.ts scripts/verify-seed-import.ts
//
// with env VERIFY_SCRATCH_DIR=<absolute dir> (fixture backups + pty transcripts go there).
//
// EVERY MNEMONIC HERE IS GENERATED BY THIS RUN (bip39.generateMnemonic). No real
// seed is read, copied or typed. SEED_ENCRYPTION_KEY and PASSPHRASE_SALT are
// random per run. Neither real fingerprint appears in this file (they are runtime arguments only).
//
// Two layers:
//   LIBRARY  replaceMasterSeed / mnemonicFromWords / writeVaultVerifier called directly.
//   CLI      the real scripts, driven through a PSEUDO-TERMINAL (util-linux `script`),
//            so "TTY only" and "echo OFF" are tested against a real tty line
//            discipline: a reader that forgot raw mode would have every typed word
//            ECHOED right after its prompt, and what follows every prompt is checked.
import crypto from "node:crypto";
import { spawn, spawnSync } from "node:child_process";
import { mkdirSync, writeFileSync, utimesSync, readFileSync, renameSync } from "node:fs";
import { isAbsolute, join } from "node:path";
import * as bip39 from "bip39";
import { prisma } from "@/db/client.js";
import { assertSandboxDatabase } from "@/db/guard.js";
import { check, checkOver, summary, thrown } from "./lib/check.js";

await assertSandboxDatabase();

const SCRATCH = process.env.VERIFY_SCRATCH_DIR ?? "";
if (!isAbsolute(SCRATCH)) {
  console.error("REFUSING: set VERIFY_SCRATCH_DIR to an absolute scratch directory (fixture backups + pty transcripts are written there).");
  process.exit(2);
}
const RUN = join(SCRATCH, `verify-seed-import-${Date.now()}`);
const BACKUP_DIR = join(RUN, "backups");
mkdirSync(BACKUP_DIR, { recursive: true });

process.env.SEED_ENCRYPTION_KEY = crypto.randomBytes(32).toString("base64");
process.env.PASSPHRASE_SALT = crypto.randomBytes(32).toString("base64");
process.env.SAMAPAY_OPS_REHEARSAL_BACKUP_DIR = BACKUP_DIR;

// Imported only after the env above exists (they read it lazily, but be explicit).
const seedMod = await import("@/chain/seed/import.js");
const { mnemonicFromWords, seedFromMnemonic, replaceMasterSeed, SeedImportRefused } = seedMod;
const masterSeedMod = await import("@/chain/seed/master-seed.js");
const { encryptSeed, seedFingerprint, loadMasterSeed, wipeMasterSeedCache } = masterSeedMod;
/** Optional access, like loadedFp: the health-poll check must also RUN on code without the export. */
const cacheState = (): { loaded: boolean; wipeArmedAt: number | null } =>
  (masterSeedMod as { seedCacheState?: () => { loaded: boolean; wipeArmedAt: number | null } }).seedCacheState?.() ?? { loaded: true, wipeArmedAt: -1 };
/** Optional access: this check must also RUN (and fail) on code that predates the export. */
const loadedFp = (): string | null | undefined => (masterSeedMod as { loadedSeedFingerprint?: () => string | null }).loadedSeedFingerprint?.();
const { writeVaultVerifier, vaultStatus, derivationStatus, VaultProofRefused } = await import("@/chain/seed/vault-proof.js");
const { verifyVaultPassphrase, encryptWithVaultKey } = await import("@/chain/seed/vault.js");
const { deriveArgon2Key, combineAndStretchKey } = await import("@/chain/seed/passphrase.js");
const { collectMnemonicWords } = await import("@/chain/seed/secret-input.js");
const { backupPathShape } = await import("@/chain/seed/ops-gate.js");

const key = Buffer.from(process.env.SEED_ENCRYPTION_KEY, "base64");

type Row = Record<string, unknown>;
async function snapshot(): Promise<string> {
  const rows = (await prisma.$queryRawUnsafe("select * from crypto_config order by id")) as Row[];
  return JSON.stringify(rows, (_k, v) => (v instanceof Date ? v.toISOString() : v));
}
async function rowCount(): Promise<number> {
  return prisma.cryptoConfig.count();
}
function codeOf(e: unknown): string {
  return (e as { code?: string } | undefined)?.code ?? "";
}

/** A 24-word mnemonic with a valid word list but a WRONG checksum (last word swapped until invalid). */
function breakChecksum(mnemonic: string): string {
  const words = mnemonic.split(" ");
  for (const w of bip39.wordlists.english ?? []) {
    const candidate = [...words.slice(0, 23), w].join(" ");
    if (w !== words[23] && !bip39.validateMnemonic(candidate)) return candidate;
  }
  throw new Error("could not break the checksum");
}

// ─── fixtures: an OLD seed (stands in for <OLD_FP>, the stored seed being replaced) and a NEW one (stands in for <NEW_FP>, the one imported)
const oldMnemonic = bip39.generateMnemonic(256);
const newMnemonic = bip39.generateMnemonic(256);
const oldSeed = await bip39.mnemonicToSeed(oldMnemonic);
const newSeed = await bip39.mnemonicToSeed(newMnemonic);
const OLD_FP = seedFingerprint(oldSeed);
const NEW_FP = seedFingerprint(newSeed);
check(OLD_FP !== NEW_FP, "fixture: two generated seeds, two fingerprints", `${OLD_FP} / ${NEW_FP}`);

async function resetToOldRow(withVerifier: boolean): Promise<void> {
  await prisma.$executeRawUnsafe("delete from crypto_config");
  let vaultVerifier: string | null = null;
  if (withVerifier) {
    const vk = combineAndStretchKey(key, await deriveArgon2Key("old-passphrase-for-the-old-seed"));
    vaultVerifier = encryptWithVaultKey(OLD_FP, vk);
  }
  await prisma.cryptoConfig.create({
    data: { id: 1, encryptedMasterSeed: encryptSeed(oldSeed, key), seedFingerprint: OLD_FP, vaultVerifier, hotWalletAddressTrc20: "T-old-hot", hotWalletAddressBep20: "0xold-hot", createdAt: new Date(Date.now() - 86_400_000) },
  });
  wipeMasterSeedCache();
}

console.log("\n── LIBRARY: words and checksum");
{
  const ok = mnemonicFromWords(newMnemonic.toUpperCase().split(" ").map((w) => `  ${w} `));
  check(ok === newMnemonic, "24 valid words (any case, padded) normalise to the mnemonic");
  const bad = await thrown(async () => mnemonicFromWords(breakChecksum(newMnemonic).split(" ")));
  check(bad.err instanceof SeedImportRefused && codeOf(bad.err) === "bad_checksum", "wrong checksum REFUSED", `${bad.name} ${codeOf(bad.err)}`);
  const notWord = await thrown(async () => mnemonicFromWords([...newMnemonic.split(" ").slice(0, 23), "notaword"]));
  check(notWord.err instanceof SeedImportRefused && codeOf(notWord.err) === "not_a_word", "a word outside the BIP39 list REFUSED", `${notWord.name} ${codeOf(notWord.err)}`);
  check(!String((notWord.err as Error | undefined)?.message ?? "").includes("notaword"), "…and the refusal does not repeat the word");
  const short = await thrown(async () => mnemonicFromWords(newMnemonic.split(" ").slice(0, 12)));
  check(codeOf(short.err) === "word_count", "12 words REFUSED (the seed is 24)", codeOf(short.err));
}

console.log("\n── LIBRARY: the word collector (injected reader, no tty)");
{
  const words = newMnemonic.split(" ");
  const answers = [words[0] ?? "", "notaword", words.slice(1, 5).join(" "), ...words.slice(5)];
  const shown: string[] = [];
  let i = 0;
  const got = await collectMnemonicWords(async () => answers[i++] ?? "", (s) => shown.push(s), 24);
  check(got.join(" ") === newMnemonic, "collector: re-asks a non-list word, accepts several words per line, stops at 24");
  const template = /^  word \d+ is not in the BIP39 English word list — type it again \(from word \d+\)\.\n$/;
  check(shown.length === 1 && shown.every((l) => template.test(l)), "collector: prints only the fixed position-only refusal line, never a typed word", JSON.stringify(shown));
}

console.log("\n── LIBRARY: replaceMasterSeed");
{
  await prisma.$executeRawUnsafe("delete from crypto_config");
  check((await derivationStatus()) === "unavailable" && (await vaultStatus()) === "unproven", "health with no seed row: derivation unavailable, vault unproven");
  const none = await thrown(() => replaceMasterSeed({ seed: newSeed, expectFingerprint: NEW_FP, replaceFingerprint: OLD_FP, apply: true }));
  check(codeOf(none.err) === "no_existing_row" && (await rowCount()) === 0, "no crypto_config row → REFUSED, nothing created", codeOf(none.err));

  await resetToOldRow(true);
  const before = await snapshot();

  const wrongFp = await thrown(() => replaceMasterSeed({ seed: newSeed, expectFingerprint: OLD_FP === "00000000" ? "11111111" : "00000000", replaceFingerprint: OLD_FP, apply: true }));
  check(codeOf(wrongFp.err) === "fingerprint_mismatch", "fingerprint ≠ --expect-fingerprint → REFUSED", codeOf(wrongFp.err));
  check((await snapshot()) === before, "…0 rows changed (full row snapshot identical)");

  const wrongReplace = await thrown(() => replaceMasterSeed({ seed: newSeed, expectFingerprint: NEW_FP, replaceFingerprint: "deadbeef", apply: true }));
  check(codeOf(wrongReplace.err) === "replace_mismatch", "existing row's fingerprint ≠ --replace-fingerprint → REFUSED", codeOf(wrongReplace.err));
  check((await snapshot()) === before, "…0 rows changed");

  const badInput = await thrown(() => replaceMasterSeed({ seed: newSeed, expectFingerprint: "A4434B0B;", replaceFingerprint: OLD_FP, apply: true }));
  check(codeOf(badInput.err) === "bad_argument", "a malformed fingerprint argument REFUSED (Zod)", codeOf(badInput.err));

  const dry = await replaceMasterSeed({ seed: newSeed, expectFingerprint: NEW_FP, replaceFingerprint: OLD_FP, apply: false });
  check(dry.outcome === "would_replace" && dry.previousFingerprint === OLD_FP, "dry run → would_replace", dry.outcome);
  check((await snapshot()) === before, "…dry run wrote nothing");

  // A second crypto_config row (id 2) must make it refuse: "exactly one row" is asserted, not assumed.
  await prisma.cryptoConfig.create({ data: { id: 2, encryptedMasterSeed: "x", seedFingerprint: OLD_FP } });
  const two = await thrown(() => replaceMasterSeed({ seed: newSeed, expectFingerprint: NEW_FP, replaceFingerprint: OLD_FP, apply: true }));
  check(codeOf(two.err) === "not_exactly_one_row", "two crypto_config rows → REFUSED", codeOf(two.err));
  await prisma.cryptoConfig.delete({ where: { id: 2 } });
  check((await snapshot()) === before, "…0 rows changed");

  // Q's probe (p0/g4 fb3cc3e review): the SAME process derives before the import —
  // the old seed is now cached — and must derive from the NEW seed after it,
  // with no cache wipe in between. A running API is exactly this process.
  const pre = await loadMasterSeed();
  check(pre.equals(oldSeed), "before the import this process holds the old seed (cache warm)");
  const t0 = Date.now();
  const done = await replaceMasterSeed({ seed: newSeed, expectFingerprint: NEW_FP, replaceFingerprint: OLD_FP, apply: true });
  check(done.outcome === "replaced" && done.fingerprint === NEW_FP, "success → replaced", done.outcome);
  const after = await prisma.cryptoConfig.findMany();
  check(after.length === 1 && after[0]?.id === 1 && after[0]?.seedFingerprint === NEW_FP, "exactly one row, id 1, new fingerprint", `${after.length} row(s)`);
  check(after[0]?.vaultVerifier === null && after[0]?.hotWalletAddressTrc20 === null && after[0]?.hotWalletAddressBep20 === null, "old seed's vault verifier + hot-wallet cache cleared (they belonged to the old seed)");
  check((after[0]?.createdAt.getTime() ?? 0) >= t0 - 1000, "created_at moved to the import time (the next backup gate is measured from it)");
  // NO wipeMasterSeedCache() here — that wipe is what hid the stale-cache bug.
  const loaded = await loadMasterSeed();
  check(loaded.equals(newSeed), "same process, warm cache, NO wipe: loadMasterSeed() returns the IMPORTED seed", `process holds ${seedFingerprint(Buffer.from(loaded))}, row ${NEW_FP}`);
  check(loadedFp() === NEW_FP, "the process's loaded fingerprint equals the row's", String(loadedFp()));
  check((await derivationStatus()) === "ready", "derivationStatus() ready only now that the process holds the row's seed");
  wipeMasterSeedCache();

  const snapAfter = await snapshot();
  const again = await replaceMasterSeed({ seed: newSeed, expectFingerprint: NEW_FP, replaceFingerprint: OLD_FP, apply: true });
  check(again.outcome === "already_imported" && (await snapshot()) === snapAfter, "re-run → already_imported, nothing written", again.outcome);
}

console.log("\n── LIBRARY: vault proof");
{
  const h0 = [await derivationStatus(), await vaultStatus()];
  check(h0[0] === "ready" && h0[1] === "unproven", "health after import: derivation ready, vault unproven", h0.join(","));
  const pass = "correct horse battery staple 42";
  const shortPass = await thrown(() => writeVaultVerifier({ passphrase: "short", apply: true }));
  check(shortPass.err instanceof VaultProofRefused && codeOf(shortPass.err) === "passphrase_too_short", "passphrase < 12 chars REFUSED", codeOf(shortPass.err));
  const before = await snapshot();
  const dry = await writeVaultVerifier({ passphrase: pass, apply: false });
  check(dry.outcome === "would_write" && (await snapshot()) === before, "dry run → would_write, nothing written", dry.outcome);
  const w = await writeVaultVerifier({ passphrase: pass, apply: true });
  check(w.outcome === "written" && w.fingerprint === NEW_FP, "apply → written", w.outcome);
  const row = await prisma.cryptoConfig.findUniqueOrThrow({ where: { id: 1 } });
  check(row.vaultVerifier !== null && (await verifyVaultPassphrase(pass, row.vaultVerifier ?? "", row.seedFingerprint)), "round trip: the stored verifier opens with the passphrase to the seed's fingerprint");
  check(!(await verifyVaultPassphrase(pass + "x", row.vaultVerifier ?? "", row.seedFingerprint)), "…and does not open with a wrong passphrase");
  check((await vaultStatus()) === "proven", "health: vault proven");
  const again = await writeVaultVerifier({ passphrase: pass, apply: true });
  check(again.outcome === "already_proven", "re-run with the same passphrase → already_proven", again.outcome);
  const other = await thrown(() => writeVaultVerifier({ passphrase: "a different passphrase entirely", apply: true }));
  check(codeOf(other.err) === "verifier_exists", "re-run with a DIFFERENT passphrase → REFUSED (never overwrites a verifier)", codeOf(other.err));
  const realKey = process.env.SEED_ENCRYPTION_KEY;
  wipeMasterSeedCache();
  delete process.env.SEED_ENCRYPTION_KEY;
  const noKey = [await derivationStatus(), await vaultStatus()];
  process.env.SEED_ENCRYPTION_KEY = realKey;
  check(noKey[0] === "unavailable" && noKey[1] === "unproven", "health with SEED_ENCRYPTION_KEY missing: derivation unavailable, vault unproven", noKey.join(","));
  process.env.SAMAPAY_EXPECTED_SEED_FINGERPRINT = OLD_FP;
  const pinnedOther = await derivationStatus();
  process.env.SAMAPAY_EXPECTED_SEED_FINGERPRINT = NEW_FP;
  const pinnedThis = await derivationStatus();
  delete process.env.SAMAPAY_EXPECTED_SEED_FINGERPRINT;
  check(pinnedOther === "unavailable" && pinnedThis === "ready", "SAMAPAY_EXPECTED_SEED_FINGERPRINT set: ready only when the row equals it", `${pinnedOther},${pinnedThis}`);
  const unsetPin = await derivationStatus();
  const malformed: string[] = [];
  for (const v of [NEW_FP.toUpperCase(), ` ${NEW_FP}`, `${NEW_FP}0`, NEW_FP.slice(0, 7), "not-hex!"]) {
    process.env.SAMAPAY_EXPECTED_SEED_FINGERPRINT = v;
    malformed.push(`${JSON.stringify(v)}=${await derivationStatus()}`);
  }
  process.env.SAMAPAY_EXPECTED_SEED_FINGERPRINT = "";
  const emptyPin = await derivationStatus();
  delete process.env.SAMAPAY_EXPECTED_SEED_FINGERPRINT;
  check(unsetPin === "ready" && emptyPin === "ready", "SAMAPAY_EXPECTED_SEED_FINGERPRINT unset (or empty, as `KEY=` in .env) keeps today's behaviour: ready", `unset=${unsetPin}, empty=${emptyPin}`);
  check(malformed.every((m) => m.endsWith("=unavailable")), "SAMAPAY_EXPECTED_SEED_FINGERPRINT malformed (uppercase, padded, 9/7 chars, non-hex) FAILS CLOSED: unavailable, never ready", malformed.join(" "));

  // /health is polled every ~10 s: it must never load the seed, never re-arm the wipe.
  wipeMasterSeedCache();
  const polls: string[] = [];
  for (let i = 0; i < 6; i++) polls.push(`${await derivationStatus()}/${await vaultStatus()}`);
  const cold = cacheState();
  check(polls.every((p) => p === "ready/proven") && !cold.loaded && cold.wipeArmedAt === null, "6 health polls on a WIPED cache: ready/proven, the seed stays UNLOADED, no wipe timer armed", `${polls[0]}, loaded=${cold.loaded}, armedAt=${cold.wipeArmedAt}`);
  await loadMasterSeed();
  const armed = cacheState().wipeArmedAt;
  await new Promise((r) => setTimeout(r, 30));
  for (let i = 0; i < 6; i++) await derivationStatus();
  const warm = cacheState();
  check(armed !== null && armed !== -1 && warm.loaded && warm.wipeArmedAt === armed, "6 health polls on a WARM cache: the wipe timer is NOT re-armed", `armed ${armed} → ${warm.wipeArmedAt}`);
  // a process holding a seed the row no longer names is "unavailable" — without reloading it
  await prisma.cryptoConfig.update({ where: { id: 1 }, data: { seedFingerprint: "ffffffff" } });
  const stale = await derivationStatus();
  const staleState = cacheState();
  await prisma.cryptoConfig.update({ where: { id: 1 }, data: { seedFingerprint: NEW_FP } });
  check(stale === "unavailable" && staleState.wipeArmedAt === armed, "cached seed ≠ row → unavailable, and health did not reload/re-arm", `${stale}`);
  wipeMasterSeedCache();
}

// ─── CLI through a pseudo-terminal
interface PtyRun { code: number | null; out: string }
/** Runs `tsx <script> <args>` inside `script` (a real pty). `steps`: when the output matches re, type text + Enter. */
function runInPty(scriptPath: string, args: string[], steps: Array<[RegExp, string]>, tag: string): Promise<PtyRun> {
  const cmd = ["./node_modules/.bin/tsx", scriptPath, ...args].map((a) => `'${a.replace(/'/g, "'\\''")}'`).join(" ");
  const transcript = join(RUN, `${tag}.typescript`);
  return new Promise((resolve) => {
    const child = spawn("script", ["-q", "-e", "-c", cmd, transcript], { stdio: ["pipe", "pipe", "pipe"], env: process.env });
    let out = "";
    let next = 0;
    let busy = false;
    const pump = () => {
      if (busy) return;
      const step = steps[next];
      if (!step) return;
      const tail = out.slice(-400);
      if (!step[0].test(tail)) return;
      busy = true;
      next += 1;
      // Keystrokes as a human types them, one chunk after the prompt appeared.
      setTimeout(() => { child.stdin.write(`${step[1]}\r`); busy = false; setTimeout(pump, 150); }, 120);
    };
    child.stdout.on("data", (d: Buffer) => { out += d.toString("utf8"); pump(); });
    child.stderr.on("data", (d: Buffer) => { out += d.toString("utf8"); });
    const timer = setTimeout(() => child.kill("SIGTERM"), 90_000);
    child.on("close", (code) => { clearTimeout(timer); writeFileSync(join(RUN, `${tag}.out`), out); resolve({ code, out }); });
  });
}

/** A backup fixture the gate accepts: samapay-<stamp>.dump.gpg, > 10 KiB, with its bare-hex .sha256 sidecar. */
function freshBackup(): string {
  const d = new Date(Date.now() + 2000);
  const stamp = d.toISOString().replace(/[-:]/g, "").replace(/\.\d{3}Z$/, "Z");
  const s = `${stamp.slice(0, 4)}-${stamp.slice(4, 6)}-${stamp.slice(6, 11)}${stamp.slice(11)}`;
  const p = join(BACKUP_DIR, `samapay-${s}.dump.gpg`);
  const body = crypto.randomBytes(20_000);
  writeFileSync(p, body);
  writeFileSync(`${p}.sha256`, crypto.createHash("sha256").update(body).digest("hex") + "\n");
  const t = (d.getTime() + 1000) / 1000;
  utimesSync(p, t, t);
  return p;
}
/**
 * What the terminal showed after each "word N of 24: " prompt, up to the line end.
 * In cooked (echo ON) mode the kernel echoes the typed word right there; with echo
 * OFF every one of these is empty. Returns the prompts that showed anything.
 * (Not a search of the whole output for mnemonic words: BIP39 words are common
 * English — "again", "list", "type" — and the script's own text can contain them.)
 */
function echoedAfterPrompts(text: string): { prompts: number; echoed: number } {
  const all = [...text.matchAll(/word \d+ of 24: ([^\r\n]*)/g)];
  return { prompts: all.length, echoed: all.filter((m) => (m[1] ?? "").length > 0).length };
}

console.log("\n── CLI: TTY gate (no pty)");
{
  const env = { ...process.env };
  delete env.DATABASE_URL; // a script that touched the DB first would fail on THIS, not on the tty check
  for (const s of ["scripts/import-master-seed.ts", "scripts/prove-vault.ts"]) {
    const r = spawnSync("./node_modules/.bin/tsx", [s, `--expect-fingerprint=${NEW_FP}`, `--replace-fingerprint=${OLD_FP}`].slice(0, s.includes("import") ? 3 : 1), { env, encoding: "utf8", input: "" });
    const all = `${r.stdout}${r.stderr}`;
    check(r.status === 1 && /REFUSING: not an interactive terminal/.test(all) && !/DATABASE_URL|prisma|Prisma/.test(all), `${s}: stdin/stdout not a TTY → REFUSED before any DB access`, `exit ${r.status}: ${all.trim().split("\n")[0]}`);
  }
}

console.log("\n── LIBRARY: backup path shape");
{
  const d = "/x/backups";
  check("stampMs" in backupPathShape(`${d}/samapay-2026-09-24T101500Z.dump.gpg`, d), "samapay-backup.sh's samapay-<stamp>.dump.gpg name is accepted");
  check("problem" in backupPathShape(`${d}/samapay-2026-09-24T101500Z.dump`, d), "an unencrypted .dump is refused");
  check("problem" in backupPathShape(`${d}/samaprime-2026-09-24T101500Z.dump.gpg`, d), "the SamaPrime database's dump is refused (wrong database)");
  check("problem" in backupPathShape(`/elsewhere/samapay-2026-09-24T101500Z.dump.gpg`, d), "a dump outside the backup dir is refused");
  check("problem" in backupPathShape(`${d}/samapay-2026-02-30T101500Z.dump.gpg`, d), "an impossible stamp is refused");
  check("problem" in backupPathShape(`samapay-2026-09-24T101500Z.dump.gpg`, d), "a relative path is refused");
  const { PROD_BACKUP_DIR } = await import("@/chain/seed/ops-gate.js");
  check(PROD_BACKUP_DIR === "/root/backups/samapay" && "stampMs" in backupPathShape("/root/backups/samapay/samapay-2026-09-24T101500Z.dump.gpg", PROD_BACKUP_DIR), "production dir is /root/backups/samapay (samapay-backup.sh's DEST)");
}

console.log("\n── CLI: import through a pty");
{
  await resetToOldRow(true);
  const before = await snapshot();
  const words = newMnemonic.split(" ");
  const wordSteps: Array<[RegExp, string]> = words.map((w, i) => [new RegExp(`word ${i + 1} of 24: $`), w]);

  // a seed word in argv: refused, and the refusal does not print it
  const w = [...newMnemonic.split(" ")].sort((a, b) => b.length - a.length)[0] ?? "";
  const argvWord = await runInPty("scripts/import-master-seed.ts", [w, `--expect-fingerprint=${NEW_FP}`, `--replace-fingerprint=${OLD_FP}`], [], "import-argv-word");
  check(argvWord.code === 1 && /unknown argument #1 \(not printed\)/.test(argvWord.out) && !argvWord.out.includes(w), "pty: a word in argv → REFUSED without printing it", `exit ${argvWord.code}`);

  // wrong expected fingerprint: every word typed, refused, nothing written
  const bad = await runInPty("scripts/import-master-seed.ts", ["--rehearsal", "--expect-fingerprint=00000000", `--replace-fingerprint=${OLD_FP}`, "--apply", `--backup=${freshBackup()}`], wordSteps, "import-wrong-fp");
  check(bad.code === 1 && /REFUSED.*fingerprint/.test(bad.out), "pty: wrong --expect-fingerprint → REFUSED (exit 1)", `exit ${bad.code}`);
  check((await snapshot()) === before, "pty: …0 rows changed");

  // --apply without --backup: refused BEFORE a single word is asked for
  const nob = await runInPty("scripts/import-master-seed.ts", ["--rehearsal", `--expect-fingerprint=${NEW_FP}`, `--replace-fingerprint=${OLD_FP}`, "--apply"], [], "import-no-backup");
  check(nob.code === 1 && /--backup/.test(nob.out) && !/word 1 of 24/.test(nob.out), "pty: --apply without --backup → REFUSED before asking for words", `exit ${nob.code}`);

  // the sidecar is REQUIRED and must match
  const badSide = freshBackup();
  writeFileSync(`${badSide}.sha256`, "0".repeat(64) + "\n");
  const bs = await runInPty("scripts/import-master-seed.ts", ["--rehearsal", `--expect-fingerprint=${NEW_FP}`, `--replace-fingerprint=${OLD_FP}`, "--apply", `--backup=${badSide}`], [], "import-bad-sidecar");
  check(bs.code === 1 && /does not match its .sha256 sidecar/.test(bs.out) && !/word 1 of 24/.test(bs.out), "pty: a sidecar that does not match → REFUSED before asking for words", `exit ${bs.code}`);
  const fresh = freshBackup();
  renameSync(`${fresh}.sha256`, `${fresh}.sha256.moved`);
  const ns = await runInPty("scripts/import-master-seed.ts", ["--rehearsal", `--expect-fingerprint=${NEW_FP}`, `--replace-fingerprint=${OLD_FP}`, "--apply", `--backup=${fresh}`], [], "import-no-sidecar");
  check(ns.code === 1 && /has no \.sha256 sidecar/.test(ns.out) && !/word 1 of 24/.test(ns.out), "pty: a dump with NO sidecar → REFUSED before asking for words", `exit ${ns.code}`);

  // a stale backup (older than the crypto_config row) is refused
  const stale = freshBackup();
  const old = (Date.now() - 3 * 86_400_000) / 1000;
  utimesSync(stale, old, old);
  const st = await runInPty("scripts/import-master-seed.ts", ["--rehearsal", `--expect-fingerprint=${NEW_FP}`, `--replace-fingerprint=${OLD_FP}`, "--apply", `--backup=${stale}`], [], "import-stale-backup");
  check(st.code === 1 && /minutes old|before the time in its own name|not newer/.test(st.out), "pty: a stale backup → REFUSED", `exit ${st.code}`);

  // dry run: words typed, checksum + fingerprint verified, nothing written
  const paste = await runInPty("scripts/import-master-seed.ts", ["--rehearsal", `--expect-fingerprint=${NEW_FP}`, `--replace-fingerprint=${OLD_FP}`], [[/word 1 of 24: $/, words.join("\r")]], "import-paste");
  const pe = echoedAfterPrompts(paste.out);
  check(paste.code === 0 && /DRY RUN/.test(paste.out) && pe.prompts === 24 && pe.echoed === 0, "pty: 24 words PASTED as one newline-separated chunk → all consumed, dry run exit 0, nothing echoed", `exit ${paste.code}, ${pe.prompts} prompts, ${pe.echoed} echoed`);
  check((await snapshot()) === before, "pty: …paste dry run wrote nothing");

  const dry = await runInPty("scripts/import-master-seed.ts", ["--rehearsal", `--expect-fingerprint=${NEW_FP}`, `--replace-fingerprint=${OLD_FP}`], wordSteps, "import-dry");
  check(dry.code === 0 && /DRY RUN/.test(dry.out) && dry.out.includes(NEW_FP), "pty: dry run (default) → exit 0, prints the fingerprint", `exit ${dry.code}`);
  check((await snapshot()) === before, "pty: …dry run wrote nothing");

  // success
  const ok = await runInPty("scripts/import-master-seed.ts", ["--rehearsal", `--expect-fingerprint=${NEW_FP}`, `--replace-fingerprint=${OLD_FP}`, "--apply", `--backup=${freshBackup()}`], wordSteps, "import-apply");
  const rows = await prisma.cryptoConfig.findMany();
  check(ok.code === 0 && rows.length === 1 && rows[0]?.seedFingerprint === NEW_FP, "pty: --apply → exactly one row, now the imported fingerprint", `exit ${ok.code}, ${rows.length} row(s)`);
  const e = [bad, dry, ok].map((r) => echoedAfterPrompts(r.out)).reduce((a, b) => ({ prompts: a.prompts + b.prompts, echoed: a.echoed + b.echoed }));
  checkOver(e.prompts, e.prompts === 72 && e.echoed === 0, "pty: ECHO OFF — nothing displayed after any word prompt", `${e.echoed} echoed`);
  // The run directory is printed (backup path) and itself holds 8-hex runs — strip it before looking.
  const printedFps = [...new Set(ok.out.split(RUN).join("<run>").match(/\b[0-9a-f]{8}\b/g) ?? [])];
  check(printedFps.includes(NEW_FP) && printedFps.every((f) => f === NEW_FP || f === OLD_FP), "pty: the only secrets-adjacent output is fingerprints", printedFps.join(","));
  const t = echoedAfterPrompts(readFileSync(join(RUN, "import-apply.typescript"), "utf8"));
  checkOver(t.prompts, t.echoed === 0, "pty: the pty's own transcript file shows no echo either", `${t.echoed} echoed`);
}

console.log("\n── CLI: prove-vault through a pty");
{
  const pass = "a passphrase typed at the tty 7";
  check((await vaultStatus()) === "unproven", "before prove-vault: vault unproven");
  const mism = await runInPty("scripts/prove-vault.ts", ["--rehearsal", "--apply", `--backup=${freshBackup()}`], [[/New vault passphrase: $/, pass], [/Type it again: $/, pass + "!"]], "vault-mismatch");
  check(mism.code === 1 && /did not match/.test(mism.out) && (await vaultStatus()) === "unproven", "pty: two different entries → REFUSED, still unproven", `exit ${mism.code}`);
  const ok = await runInPty("scripts/prove-vault.ts", ["--rehearsal", "--apply"], [[/New vault passphrase: $/, pass], [/Type it again: $/, pass]], "vault-apply");
  check(ok.code === 0 && /vault: proven/.test(ok.out), "pty: prove-vault --apply (no --backup, runbook §4) → exit 0, prints vault: proven", `exit ${ok.code}`);
  check((await vaultStatus()) === "proven", "health: vault proven after the CLI");
  check(!ok.out.includes(pass) && !ok.out.includes("typed at the tty"), "pty: ECHO OFF — the passphrase is not in what the terminal displayed");
}

await prisma.$disconnect();
console.log(`\nartifacts: ${RUN}`);
process.exit(summary());
